name: Python Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Create virtual environment
      - name: Create virtual environment
        run: python -m venv venv

      # 4️⃣ Activate venv and install dependencies
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 5️⃣ Optional: Run tests
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      # 6️⃣ Optional: Deploy (example)
      # - name: Deploy
      #   run: |
      #     source venv/bin/activate
      #     python deploy_script.py
